name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
categories:
  - title: Major Changes
    label: "change: major"

  - title: Minor Changes
    label: "change: minor"

  - title: Patch Changes
    label: "change: patch"

  - title: Other Changes

template: |
  $CHANGES
