language: java

install: true

jdk:
  - openjdk11

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build
  - ./gradlew bintrayUpload -DbintrayUser=$BINTRAY_USER -DbintrayKey=$BINTRAY_KEY
