group = com.apollographql.federation
version = 7.0-SNAPSHOT

# dependencies
annotationsVersion = 26.1.0
graphQLJavaVersion = 26.0
# generated proto v3 messages can be used with v3 and v4
protobufVersion = 3.25.9
slf4jVersion = 2.0.19
springBootVersion = 4.1.1

# test dependencies
junitPlatformVersion = 1.14.4
junitVersion = 5.14.4
mockWebServerVersion = 5.5.0
springGraphQLVersion = 2.0.5
reactorVersion = 3.8.7
