spring:
  application:
    name: federation-jvm-compatibility
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    http:
      path: /
server:
  port: 4001
