name: Pull Request Federation Compatibility Check

on:
  workflow_call:
    secrets:
      token:
        required: false

jobs:
  compatibility:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build app with Gradle
        run: ./gradlew bootJar

      - name: Compatibility Test
        uses: apollographql/federation-subgraph-compatibility@v2
        with:
          compose: 'docker-compose.yaml'
          schema: 'src/main/resources/graphql/schema.graphqls'
          failOnWarning: true
          failOnRequired: true
          workingDirectory: 'compatibility'
          token: ${{ secrets.token }}
