name: Federation Compatibility

on:
  workflow_call:

jobs:
  compatibility:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: compatibility

    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build app with Gradle
        run: ./gradlew bootJar

      - name: Compatibility Test
        run:  npx --yes @apollo/federation-subgraph-compatibility docker --debug --compose docker-compose.yaml --schema src/main/resources/graphql/schema.graphqls

      - name: Generate Results Summary
        run: |
          cat results.md
          cat results.md >> $GITHUB_STEP_SUMMARY
