name: Pull Request Federation Compatibility Check

on:
  pull_request_target:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  integration:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Build app with Gradle
        run: ./gradlew bootJar

      - name: Compatibility Test
        uses: apollographql/federation-subgraph-compatibility@v1
        with:
          compose: 'docker-compose.yaml'
          schema: 'src/main/resources/graphql/schema.graphqls'
          debug: true
          token: ${{ secrets.PAT }}
          failOnWarning: true
          failOnRequired: true
          workingDirectory: 'compatibility'
