name: Pull Request Check

on:
  pull_request_target:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  integration:
    uses: ./.github/workflows/federation-compatibility.yaml
    with:
      fork: true
    secrets:
      token: ${{ secrets.PAT }}
